name: Build docker image

on:
  workflow_dispatch:

jobs:
  docker-build:
  runs-on: ubuntu-latest

  step:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup python enviornment
      uses: actions/setup-python@v6
      with:
          python-version: '3.13' 
 
    - name: Install dependencies
      run: |
         python -m venv venv
         source venv/bin/activate
         pip3 install ruff

    - name: Lint and format code
      run : |
         ruff check .
         ruff check --fix .
         ruff 

      

    